<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <InvariantGlobalization>false</InvariantGlobalization>
    <ApplicationManifest>../../../src/Octadock.App/app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../../../src/Octadock.App/Octadock.App.csproj" /></ItemGroup>
</Project>
